### ISSUE TITLE
Desabilitar o SSL quando estiver no ambiente DEV

### ISSUE THREAD

**Issue by lpirola** [redelivre/login-cidadao#39]
Ao remover todos os `, requires_channel: https` nas linhas 156 a 191 é possível acessar localmente (php-cli) sem o uso do https: https://github.com/redelivre/login-cidadao/blob/master/app/config/security.yml#L156-L191

Qual seria a melhor forma de implementar isso de forma configurável?

**Comment by guilhermednt** [comment]
Me parece que o Symfony não suporta isso. :/

**Comment by guilhermednt** [comment]
Descobri uma forma de configurar isso. :)

**Comment by guilhermednt** [comment]
Fechando issue por inatividade.

Para referência futura: quem desejar utilizar localmente sem HTTPS basta configurar no `parameters.yml` os parâmetros `trusted_proxies` e `dev_allowed` para incluir o seu IP.

Para quem utiliza TLS Termination basta que o IP do seu load balancer ou TLS Terminator esteja corretamente compreendido nos valores de `trusted_proxies`. Mais informações [na documentação oficial](http://symfony.com/doc/2.8/request/load_balancer_reverse_proxy.html).
