### ISSUE TITLE
3rd Party Login: ask email when missing

### ISSUE THREAD

**Issue by guilhermednt** [redelivre/login-cidadao#53]
It seems that Facebook is allowing our users to connect without giving us their email, which is awesome on the privacy side of things, but we have to handle that on our side to ask the user for his or her email.

Note that Twitter never sends the user's email so it might be a good starting point to implement the same behavior on other 3rd Party Login providers or to refactor Twitter's.

**Comment by lpirola** [comment]
Knowing facebook profile or twitter isn't enough?

**Comment by guilhermednt** [comment]
Email is required, otherwise the user can't recover the account or even login if access to the 3rd party service is lost.
